os: linux

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - ${TRAVIS_BUILD_DIR}/travis/extension-cache
    - vendor

php:
   - 7.1
   - 7.2
   - 7.3
   - 7.4

before_script:
  - travis_retry composer self-update --stable -n
  - travis_retry composer update  --no-interaction --prefer-source

script:
  - composer test
  - composer test-coverage

notifications:
  email: false
